kind: pipeline
name: translate

trigger:
  branch:
    - develop
  event:
    - push

steps:
  - name: download
    pull: always
    image: jonasfranz/crowdin
    settings:
      download: true
      export_dir: internal/web/data/locale/
      ignore_branch: true
      project_identifier: lenpaste
    environment:
      CROWDIN_KEY:
        from_secret: crowdin_key

  - name: push
    pull: always
    image: appleboy/drone-git-push
    settings:
      author_email: "translatebot@lcomrade.su"
      author_name: Translate [Bot]
      branch: develop
      commit: true
      commit_message: "[skip ci] Updated translations"
      remote: "git@git.lcomrade.su:root/lenpaste.git"
    environment:
      GIT_PUSH_SSH_KEY:
        from_secret: ci_ssh_key

  - name: upload
    pull: always
    image: jonasfranz/crowdin
    settings:
      files:
        en.ini: internal/web/data/locale/en.locale
        ru.ini: internal/web/data/locale/ru.locale
      ignore_branch: true
      project_identifier: lenpaste
    environment:
      CROWDIN_KEY:
        from_secret: crowdin_key
