when:
  event: cron
  branch: develop

pipeline:
  download:
    image: git.lcomrade.su/root/drone-crowdin-v2
    pull: true
    settings:
      crowdin_key:
        from_secret: crowdin_key
      project_id: 553341
      target: download
      download_to: internal/web/data/locale/
      #download_skip_untranslated_strings: true
      download_skip_untranslated_files: true
      #download_export_approved_only: false
      when:
        event: cron

  push:
    image: appleboy/drone-git-push
    pull: true
    settings:
      author_email: "translatebot@lcomrade.su"
      author_name: Translate [Bot]
      branch: develop
      commit: true
      commit_message: "[skip ci] Updated translations"
      remote: "git@git.lcomrade.su:root/lenpaste.git"
      ssh_key:
        from_secret: ci_ssh_key
      when:
        event: cron
