when:
  event: [push, pull_request]
  branch: develop
  path: ["**/*.sh", ".woodpecker/test_shell.yml"]

pipeline:
  build:
    image: koalaman/shellcheck-alpine
    pull: true
    commands:
      - shellcheck --version
      - shellcheck $(find ./ -type f -name '*.sh')
