when:
  event: [push, pull_request]
  branch: develop
  path: ["Dockerfile", ".woodpecker/test_docker.yml"]

pipeline:
  check:
    image: hadolint/hadolint
    pull: true
    commands:
      - hadolint --version
      - hadolint  Dockerfile
