name: CI to Docker Hub (stable)
on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Save version information
        shell: bash
        run: |-
          echo "{" > ./version.json
          echo '    "Version":"'$GITHUB_REF'-stable",' >> ./version.json
          echo '    "GitTag":"'$GITHUB_REF'",' >> ./version.json
          echo '    "GitCommit":"'$(git log -1 --pretty=%H)'",' >> ./version.json
          echo '    "BuildDate":"'$(date +%d.%m.%Y)'"' >> ./version.json
          echo "}" >> ./version.json

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lenpaste:stable

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
